import { beforeEach,describe,expect,it,vi } from "vitest";
const mocks=vi.hoisted(()=>({capture:vi.fn(),user:null as null|{id:string}}));
vi.mock("@/lib/analytics/store",()=>({captureAnalyticsEvent:mocks.capture}));
vi.mock("@/lib/security/session",()=>({getCurrentUser:vi.fn(async()=>mocks.user)}));
vi.mock("@/lib/rate-limit",()=>({enforceRateLimit:vi.fn(),requestKey:vi.fn(()=>"analytics-key")}));

describe("analytics capture route",()=>{beforeEach(()=>{mocks.user=null;mocks.capture.mockResolvedValue({accepted:true,inserted:true,eventId:"analytics-id"});});
  it("captures a reduced anonymous client event",async()=>{const{POST}=await import("@/app/api/analytics/route");const response=await POST(new Request("http://localhost/api/analytics",{method:"POST",headers:{"content-type":"application/json","user-agent":"Mozilla Chrome/140 private-full-agent"},body:JSON.stringify({eventName:"page_view",deduplicationKey:"page:/events:1",anonymousSessionId:"11111111-1111-4111-8111-111111111111",utmCampaign:"winter",metadata:{path:"/events",email:"private@example.test"}})}));expect(response.status).toBe(201);expect(mocks.capture).toHaveBeenCalledWith(expect.objectContaining({eventName:"page_view",source:"client",browserFamily:"chrome",deviceCategory:"desktop",utmCampaign:"winter",safeMetadata:{path:"/events"}}));const recorded=JSON.stringify(mocks.capture.mock.calls[0][0]);expect(recorded).not.toContain("private-full-agent");expect(recorded).not.toContain("private@example.test");expect(recorded).not.toContain("11111111-1111");});
  it("associates an authenticated customer only when available",async()=>{mocks.user={id:"customer-id"};const{POST}=await import("@/app/api/analytics/route");await POST(new Request("http://localhost/api/analytics",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({eventName:"video_started",deduplicationKey:"media:started",anonymousSessionId:"22222222-2222-4222-8222-222222222222",eventId:"event-a"})}));expect(mocks.capture).toHaveBeenCalledWith(expect.objectContaining({customerId:"customer-id"}));});
  it("rejects client attempts to claim authoritative payment events",async()=>{const{POST}=await import("@/app/api/analytics/route");const response=await POST(new Request("http://localhost/api/analytics",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({eventName:"payment_completed",deduplicationKey:"fake-payment",anonymousSessionId:"33333333-3333-4333-8333-333333333333"})}));expect(response.status).toBe(422);expect(mocks.capture).not.toHaveBeenCalled();});
});
